version: '3.8'
services:
  kali-docker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PACKAGES_FILE: packages.txt
    image: kali-docker:latest
    container_name: kali-docker
    tty: true
    stdin_open: true
    ports:
      - "2223:2222"   # porta host:container
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - kali-docker-home:/root
      - kali-docker-apt-cache:/var/cache/apt/archives
    restart: unless-stopped

volumes:
  kali-docker-home:
  kali-docker-apt-cache:
